version: "3.8"

services:
  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: https://api.buytly.com/api/v1
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: 974512491943-cn69krek1s1ektd5q4qeg2g4ao3ssvbr.apps.googleusercontent.com
    environment:
      NEXT_PUBLIC_API_URL: https://api.buytly.com/api/v1
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: 974512491943-cn69krek1s1ektd5q4qeg2g4ao3ssvbr.apps.googleusercontent.com
    ports:
      - "3025:3000"
    restart: always

  server:
    build:
      context: ./server
    ports:
      - "5025:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/gcs-service-account.json:/app/gcs-service-account.json:ro
    restart: always
