export const SEED_DOMAIN = "buytly.demo";

export const SEED_USERS = [
  {
    key: "admin",
    email: `admin@${SEED_DOMAIN}`,
    role: "admin",
    firstName: "Amina",
    lastName: "Rahman",
    phoneCountryCode: "+971",
    phoneNumber: "501000001",
  },
  {
    key: "seller",
    email: `seller@${SEED_DOMAIN}`,
    role: "seller",
    firstName: "Omar",
    lastName: "Hassan",
    phoneCountryCode: "+971",
    phoneNumber: "501000002",
  },
  {
    key: "seller2",
    email: `seller2@${SEED_DOMAIN}`,
    role: "seller",
    firstName: "Layla",
    lastName: "Farouk",
    phoneCountryCode: "+971",
    phoneNumber: "501000003",
  },
  {
    key: "agent",
    email: `agent@${SEED_DOMAIN}`,
    role: "agent",
    firstName: "James",
    lastName: "Carter",
    phoneCountryCode: "+971",
    phoneNumber: "501000004",
  },
  {
    key: "agent2",
    email: `agent2@${SEED_DOMAIN}`,
    role: "agent",
    firstName: "Sara",
    lastName: "Menon",
    phoneCountryCode: "+971",
    phoneNumber: "501000005",
  },
  {
    key: "buyer",
    email: `buyer@${SEED_DOMAIN}`,
    role: "buyer",
    firstName: "Noah",
    lastName: "Patel",
    phoneCountryCode: "+971",
    phoneNumber: "501000006",
    preferences: {
      budgetMin: 500000,
      budgetMax: 2500000,
      locations: ["Dubai", "Abu Dhabi"],
      propertyTypes: ["apartment", "villa"],
    },
  },
  {
    key: "buyer2",
    email: `buyer2@${SEED_DOMAIN}`,
    role: "buyer",
    firstName: "Mia",
    lastName: "Khan",
    phoneCountryCode: "+971",
    phoneNumber: "501000007",
    preferences: {
      budgetMin: 80000,
      budgetMax: 180000,
      locations: ["Dubai"],
      propertyTypes: ["apartment", "studio"],
    },
  },
];

export const SEED_AGENT_PROFILES = [
  {
    userKey: "agent",
    licenseNumber: "BRN-784512",
    agency: "Buytly Realty Dubai",
    city: "Dubai",
    bio: "Luxury waterfront specialist with 10+ years in Dubai Marina and Downtown.",
    specialties: ["Luxury", "Waterfront", "Off-plan"],
    rating: 4.8,
    reviewCount: 42,
    isVerified: true,
  },
  {
    userKey: "agent2",
    licenseNumber: "BRN-903311",
    agency: "Buytly Realty Abu Dhabi",
    city: "Abu Dhabi",
    bio: "Focused on family villas and investment apartments across the UAE capital.",
    specialties: ["Family homes", "Investments"],
    rating: 4.6,
    reviewCount: 28,
    isVerified: true,
  },
];

const AMENITIES = {
  standard: ["Parking", "Balcony", "Central AC", "Security"],
  premium: ["Pool", "Gym", "Concierge", "Smart Home", "Sea View"],
  rent: ["Furnished", "WiFi", "Maintenance", "Pet Friendly"],
};

export const SEED_PROPERTIES = [
  {
    ownerKey: "seller",
    agentKey: "agent",
    title: "Marina View 2BR Apartment",
    description:
      "Bright two-bedroom apartment with full marina views, open kitchen, and covered parking. Walking distance to the beach promenade.",
    type: "apartment",
    listingType: "sale",
    price: 1850000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.1415, 25.0803],
    address: "Dubai Marina Walk",
    bedrooms: 2,
    bathrooms: 2,
    area: 118,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.premium],
    viewCount: 312,
  },
  {
    ownerKey: "seller",
    agentKey: "agent",
    title: "Downtown Burj Khalifa Studio",
    description:
      "Furnished studio in the heart of Downtown with gym access and 24/7 concierge.",
    type: "studio",
    listingType: "rent",
    price: 95000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.2744, 25.1972],
    address: "Sheikh Mohammed bin Rashid Blvd",
    bedrooms: 0,
    bathrooms: 1,
    area: 48,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.rent],
    viewCount: 188,
  },
  {
    ownerKey: "seller",
    agentKey: "agent",
    title: "JVC Family Townhouse",
    description:
      "Spacious three-bedroom townhouse with private garden, maid's room, and community pool.",
    type: "townhouse",
    listingType: "sale",
    price: 2100000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.2074, 25.0598],
    address: "Jumeirah Village Circle",
    bedrooms: 3,
    bathrooms: 4,
    area: 210,
    status: "active",
    amenities: [...AMENITIES.standard, "Garden", "Community Pool"],
    viewCount: 145,
  },
  {
    ownerKey: "seller2",
    agentKey: "agent2",
    title: "Saadiyat Island Luxury Villa",
    description:
      "Five-bedroom beach-access villa with private pool and landscaped garden on Saadiyat Island.",
    type: "villa",
    listingType: "sale",
    price: 9800000,
    currency: "AED",
    city: "Abu Dhabi",
    country: "UAE",
    coordinates: [54.4396, 24.542],
    address: "Saadiyat Beach District",
    bedrooms: 5,
    bathrooms: 6,
    area: 620,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.premium, "Private Pool"],
    viewCount: 97,
  },
  {
    ownerKey: "seller2",
    agentKey: "agent2",
    title: "Al Reem Island 3BR Apartment",
    description:
      "Corner unit with city and sea views, two parking spaces, and access to rooftop lounge.",
    type: "apartment",
    listingType: "sale",
    price: 2450000,
    currency: "AED",
    city: "Abu Dhabi",
    country: "UAE",
    coordinates: [54.395, 24.496],
    address: "Al Reem Island",
    bedrooms: 3,
    bathrooms: 3,
    area: 165,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.premium],
    viewCount: 76,
  },
  {
    ownerKey: "seller",
    title: "Business Bay Canal Duplex",
    description:
      "Modern duplex penthouse overlooking the canal with floor-to-ceiling windows.",
    type: "duplex",
    listingType: "sale",
    price: 4200000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.263, 25.1865],
    address: "Business Bay",
    bedrooms: 4,
    bathrooms: 5,
    area: 320,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.premium],
    viewCount: 221,
  },
  {
    ownerKey: "seller",
    agentKey: "agent",
    title: "JLT Lake View 1BR",
    description:
      "Well-maintained one-bedroom apartment near metro with lake views and fitted kitchen.",
    type: "apartment",
    listingType: "rent",
    price: 78000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.143, 25.069],
    address: "Jumeirah Lake Towers",
    bedrooms: 1,
    bathrooms: 2,
    area: 82,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.rent],
    viewCount: 164,
  },
  {
    ownerKey: "seller2",
    title: "Sharjah Al Majaz 2BR",
    description:
      "Affordable waterfront apartment with balcony and covered parking near Al Qasba.",
    type: "apartment",
    listingType: "rent",
    price: 52000,
    currency: "AED",
    city: "Sharjah",
    country: "UAE",
    coordinates: [55.375, 25.321],
    address: "Al Majaz",
    bedrooms: 2,
    bathrooms: 2,
    area: 105,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.rent],
    viewCount: 89,
  },
  {
    ownerKey: "seller",
    agentKey: "agent",
    title: "Palm Jumeirah Garden Home",
    description:
      "Signature garden home on the Palm with private beach access and upgraded interiors.",
    type: "villa",
    listingType: "sale",
    price: 14500000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.1167, 25.1124],
    address: "Palm Jumeirah",
    bedrooms: 4,
    bathrooms: 5,
    area: 510,
    status: "active",
    amenities: [...AMENITIES.standard, ...AMENITIES.premium, "Beach Access"],
    viewCount: 402,
  },
  {
    ownerKey: "seller2",
    agentKey: "agent2",
    title: "Yas Island Investment Apartment",
    description:
      "High-yield one-bedroom near Yas Mall, ideal for short-term rental investors.",
    type: "apartment",
    listingType: "sale",
    price: 1150000,
    currency: "AED",
    city: "Abu Dhabi",
    country: "UAE",
    coordinates: [54.61, 24.467],
    address: "Yas Island",
    bedrooms: 1,
    bathrooms: 2,
    area: 72,
    status: "active",
    amenities: [...AMENITIES.standard, "Investor Ready"],
    viewCount: 133,
  },
  {
    ownerKey: "seller",
    title: "Dubai Hills Park View Villa",
    description:
      "Four-bedroom villa backing onto the park with upgraded kitchen and maid's room.",
    type: "villa",
    listingType: "sale",
    price: 5200000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.245, 25.103],
    address: "Dubai Hills Estate",
    bedrooms: 4,
    bathrooms: 5,
    area: 380,
    status: "active",
    amenities: [...AMENITIES.standard, "Park View", "Maid Room"],
    viewCount: 178,
  },
  {
    ownerKey: "seller2",
    title: "Commercial Plot DIFC Adjacent",
    description:
      "Freehold commercial land suitable for boutique office or retail development.",
    type: "commercial",
    listingType: "sale",
    price: 12000000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.278, 25.211],
    address: "Near DIFC",
    bedrooms: 0,
    bathrooms: 0,
    area: 4500,
    status: "active",
    amenities: ["Freehold", "Corner Plot"],
    viewCount: 54,
  },
  {
    ownerKey: "seller",
    title: "Pending Marina Tower Unit",
    description:
      "New listing awaiting moderation — one-bedroom with partial marina view.",
    type: "apartment",
    listingType: "sale",
    price: 1320000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.139, 25.078],
    address: "Dubai Marina",
    bedrooms: 1,
    bathrooms: 2,
    area: 76,
    status: "pending",
    amenities: AMENITIES.standard,
    viewCount: 0,
  },
  {
    ownerKey: "seller2",
    title: "Draft Hills Apartment",
    description: "Work-in-progress listing saved as draft by the seller.",
    type: "apartment",
    listingType: "rent",
    price: 68000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.24, 25.1],
    address: "Dubai Hills",
    bedrooms: 2,
    bathrooms: 2,
    area: 98,
    status: "draft",
    amenities: AMENITIES.standard,
    viewCount: 0,
  },
  {
    ownerKey: "seller",
    title: "Sold Creek Harbour 2BR",
    description: "Recently sold apartment — kept for sold-filter demos.",
    type: "apartment",
    listingType: "sale",
    price: 1750000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.348, 25.205],
    address: "Dubai Creek Harbour",
    bedrooms: 2,
    bathrooms: 2,
    area: 112,
    status: "sold",
    amenities: AMENITIES.standard,
    viewCount: 501,
  },
  {
    ownerKey: "seller2",
    title: "Rented JLT Studio",
    description:
      "Studio currently rented — visible under rented status filters.",
    type: "studio",
    listingType: "rent",
    price: 62000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.142, 25.071],
    address: "JLT Cluster A",
    bedrooms: 0,
    bathrooms: 1,
    area: 44,
    status: "rented",
    amenities: AMENITIES.rent,
    viewCount: 240,
  },
  {
    ownerKey: "seller2",
    agentKey: "agent2",
    title: "Al Shamkha Residential Land",
    description:
      "Freehold residential land plot ready for villa construction with utility connections at the boundary.",
    type: "land",
    listingType: "sale",
    price: 1850000,
    currency: "AED",
    city: "Abu Dhabi",
    country: "UAE",
    coordinates: [54.72, 24.39],
    address: "Al Shamkha South",
    bedrooms: 0,
    bathrooms: 0,
    area: 1200,
    status: "active",
    amenities: ["Freehold", "Corner Plot", "Utility Ready"],
    viewCount: 41,
  },
  {
    ownerKey: "seller",
    title: "Archived Legacy Marina Loft",
    description:
      "Former listing withdrawn by seller — retained for archive dashboard demos.",
    type: "apartment",
    listingType: "sale",
    price: 990000,
    currency: "AED",
    city: "Dubai",
    country: "UAE",
    coordinates: [55.137, 25.076],
    address: "Dubai Marina",
    bedrooms: 1,
    bathrooms: 1,
    area: 68,
    status: "archived",
    amenities: AMENITIES.standard,
    viewCount: 12,
  },
];

export const SEED_REVIEWS = [
  {
    propertyTitle: "Marina View 2BR Apartment",
    buyerKey: "buyer",
    rating: 5,
    title: "Excellent location",
    text: "Loved the marina view and building amenities. Viewing was easy to schedule.",
  },
  {
    propertyTitle: "Downtown Burj Khalifa Studio",
    buyerKey: "buyer2",
    rating: 4,
    title: "Great for singles",
    text: "Compact but well finished. Noise picks up on event nights.",
  },
  {
    propertyTitle: "JVC Family Townhouse",
    buyerKey: "buyer",
    rating: 5,
    title: "Perfect for families",
    text: "Garden space is a huge plus. Schools and retail nearby.",
  },
  {
    propertyTitle: "Palm Jumeirah Garden Home",
    buyerKey: "buyer2",
    rating: 5,
    title: "Dream home",
    text: "Private beach access and spacious layout exceeded expectations.",
  },
  {
    propertyTitle: "JLT Lake View 1BR",
    buyerKey: "buyer",
    rating: 4,
    title: "Solid rental",
    text: "Good value for JLT. Building is well maintained.",
  },
  {
    propertyTitle: "Saadiyat Island Luxury Villa",
    buyerKey: "buyer",
    rating: 5,
    title: "Stunning property",
    text: "The beach access and finishes are world class. Agent was very responsive.",
  },
  {
    propertyTitle: "Al Reem Island 3BR Apartment",
    buyerKey: "buyer2",
    rating: 4,
    title: "Great views",
    text: "Corner unit layout works well. Building amenities are premium.",
  },
  {
    propertyTitle: "Yas Island Investment Apartment",
    buyerKey: "buyer",
    rating: 4,
    title: "Solid investment",
    text: "Rental yield looks strong near Yas Mall. Good for short-term lets.",
  },
];

export const SEED_SAVED_SEARCHES = [
  {
    userKey: "buyer",
    name: "Dubai sale apartments",
    filters: {
      listingType: "sale",
      city: "Dubai",
      type: "apartment",
      minPrice: 500000,
      maxPrice: 2500000,
    },
  },
  {
    userKey: "buyer2",
    name: "Marina rentals",
    filters: {
      listingType: "rent",
      city: "Dubai",
      search: "marina",
    },
  },
];

/** Expected document counts after a full seed (used by smoke tests). */
export const SEED_EXPECTED_COUNTS = {
  users: SEED_USERS.length,
  agentProfiles: SEED_AGENT_PROFILES.length,
  properties: SEED_PROPERTIES.length,
  reviews: SEED_REVIEWS.length,
  favorites: 4,
  bookings: 3,
  transactions: 2,
  savedSearches: SEED_SAVED_SEARCHES.length,
  notifications: 4,
};
