/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectId } from "./objectId";
import type { AgentProfileUserId } from "./agentProfileUserId";

export interface AgentProfile {
  _id?: ObjectId;
  userId?: AgentProfileUserId;
  licenseNumber?: string;
  agency?: string;
  bio?: string;
  specialties?: string[];
  city?: string;
  /**
   * @minimum 0
   * @maximum 5
   */
  rating?: number;
  reviewCount?: number;
  isVerified?: boolean;
  /** Active listings count (computed on list/detail) */
  listingsCount?: number;
  createdAt?: string;
  updatedAt?: string;
}
