/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectId } from "./objectId";
import type { BookingPropertyId } from "./bookingPropertyId";
import type { BookingBuyerId } from "./bookingBuyerId";
import type { BookingAgentId } from "./bookingAgentId";
import type { BookingStatus } from "./bookingStatus";

export interface Booking {
  _id?: ObjectId;
  propertyId?: BookingPropertyId;
  buyerId?: BookingBuyerId;
  agentId?: BookingAgentId;
  scheduledAt?: string;
  message?: string;
  status?: BookingStatus;
  agentNotes?: string;
  createdAt?: string;
  updatedAt?: string;
}
