/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { PropertyType } from "./propertyType";
import type { ListingType } from "./listingType";
import type { PropertyLocation } from "./propertyLocation";
import type { PropertyStatus } from "./propertyStatus";
import type { ObjectId } from "./objectId";

export interface CreatePropertyRequest {
  /**
   * @minLength 3
   * @maxLength 200
   */
  title: string;
  /** @minLength 10 */
  description: string;
  type: PropertyType;
  listingType: ListingType;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  price: number;
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  location: PropertyLocation;
  /** @minimum 0 */
  bedrooms?: number;
  /** @minimum 0 */
  bathrooms?: number;
  area?: number;
  areaUnit?: string;
  amenities?: string[];
  status?: PropertyStatus;
  agentId?: ObjectId;
}
