/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectId } from "./objectId";
import type { TransactionType } from "./transactionType";

export interface CreateTransactionRequest {
  propertyId: ObjectId;
  type: TransactionType;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  amount: number;
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** @maxLength 2000 */
  notes?: string;
}
