/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { HealthDataServicesMongodb } from "./healthDataServicesMongodb";
import type { HealthDataServicesRedis } from "./healthDataServicesRedis";

export type HealthDataServices = {
  mongodb: HealthDataServicesMongodb;
  /** not_configured when REDIS_URL is unset; disconnected when configured but unreachable */
  redis: HealthDataServicesRedis;
};
