/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { HealthDataStatus } from "./healthDataStatus";
import type { HealthDataServices } from "./healthDataServices";

export interface HealthData {
  status: HealthDataStatus;
  timestamp: string;
  services: HealthDataServices;
}
