/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { PageParamParameter } from "./pageParamParameter";
import type { LimitParamParameter } from "./limitParamParameter";

export type ListAgentsParams = {
  /**
   * Page number (1-based)
   * @minimum 1
   */
  page?: PageParamParameter;
  /**
   * Items per page (max 100)
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParamParameter;
  city?: string;
  specialty?: string;
};
