/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { PageParamParameter } from "./pageParamParameter";
import type { LimitParamParameter } from "./limitParamParameter";
import type { PropertyType } from "./propertyType";
import type { ListingType } from "./listingType";
import type { PropertyStatus } from "./propertyStatus";
import type { ListPropertiesSortBy } from "./listPropertiesSortBy";
import type { ListPropertiesSortOrder } from "./listPropertiesSortOrder";

export type ListPropertiesParams = {
  /**
   * Page number (1-based)
   * @minimum 1
   */
  page?: PageParamParameter;
  /**
   * Items per page (max 100)
   * @minimum 1
   * @maximum 100
   */
  limit?: LimitParamParameter;
  minPrice?: number;
  maxPrice?: number;
  type?: PropertyType;
  listingType?: ListingType;
  status?: PropertyStatus;
  city?: string;
  bedrooms?: number;
  /**
   * Full-text search on title and description
   */
  search?: string;
  /**
   * Latitude for geo-radius search (requires lng and radiusKm)
   */
  lat?: number;
  /**
   * Longitude for geo-radius search
   */
  lng?: number;
  /**
   * Search radius in kilometers
   */
  radiusKm?: number;
  sortBy?: ListPropertiesSortBy;
  sortOrder?: ListPropertiesSortOrder;
};
