/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectId } from "./objectId";
import type { NotificationType } from "./notificationType";
import type { NotificationData } from "./notificationData";
import type { NotificationChannels } from "./notificationChannels";

export interface Notification {
  _id?: ObjectId;
  userId?: ObjectId;
  type?: NotificationType;
  title?: string;
  message?: string;
  data?: NotificationData;
  isRead?: boolean;
  /** @nullable */
  readAt?: string | null;
  channels?: NotificationChannels;
  createdAt?: string;
  updatedAt?: string;
}
