/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectId } from "./objectId";
import type { PropertyType } from "./propertyType";
import type { ListingType } from "./listingType";
import type { PropertyLocation } from "./propertyLocation";
import type { PropertyStatus } from "./propertyStatus";
import type { PropertyMedia } from "./propertyMedia";
import type { PropertyAgentId } from "./propertyAgentId";
import type { PropertyOwnerId } from "./propertyOwnerId";

export interface Property {
  _id?: ObjectId;
  title?: string;
  slug?: string;
  description?: string;
  type?: PropertyType;
  listingType?: ListingType;
  price?: number;
  currency?: string;
  location?: PropertyLocation;
  bedrooms?: number;
  bathrooms?: number;
  area?: number;
  areaUnit?: string;
  amenities?: string[];
  status?: PropertyStatus;
  media?: PropertyMedia[];
  agentId?: PropertyAgentId;
  ownerId?: PropertyOwnerId;
  viewCount?: number;
  createdAt?: string;
  updatedAt?: string;
}
