/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterRequestRole } from "./registerRequestRole";

export interface RegisterRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /** @minLength 8 */
  confirmPassword: string;
  /** @maxLength 50 */
  firstName?: string;
  /** @maxLength 50 */
  lastName?: string;
  /** @maxLength 20 */
  phone?: string;
  role?: RegisterRequestRole;
}
