/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectId } from "./objectId";
import type { TransactionPropertyId } from "./transactionPropertyId";
import type { TransactionBuyerId } from "./transactionBuyerId";
import type { TransactionSellerId } from "./transactionSellerId";
import type { TransactionAgentId } from "./transactionAgentId";
import type { TransactionType } from "./transactionType";
import type { TransactionStatus } from "./transactionStatus";

export interface Transaction {
  _id?: ObjectId;
  propertyId?: TransactionPropertyId;
  buyerId?: TransactionBuyerId;
  sellerId?: TransactionSellerId;
  agentId?: TransactionAgentId;
  type?: TransactionType;
  amount?: number;
  currency?: string;
  status?: TransactionStatus;
  notes?: string;
  /** @nullable */
  completedAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
}
