/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateMyAgentProfileBody = {
  /** @maxLength 50 */
  licenseNumber?: string;
  /** @maxLength 100 */
  agency?: string;
  /** @maxLength 2000 */
  bio?: string;
  specialties?: string[];
  /** @maxLength 100 */
  city?: string;
};
