/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateBookingStatusRequestStatus =
  (typeof UpdateBookingStatusRequestStatus)[keyof typeof UpdateBookingStatusRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateBookingStatusRequestStatus = {
  approved: "approved",
  rejected: "rejected",
  completed: "completed",
} as const;
