/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Buytly API
 * Production-ready real estate marketplace backend API. All successful responses use `{ success, message, data }`. Paginated lists add a top-level `pagination` object. OpenAPI spec is Orval-compatible — each operation has an `operationId`.
 * OpenAPI spec version: 1.0.0
 */
import type { ObjectId } from "./objectId";
import type { UserRole } from "./userRole";
import type { Avatar } from "./avatar";
import type { UserPreferences } from "./userPreferences";

/**
 * Authenticated user profile (public fields)
 */
export interface User {
  id?: ObjectId;
  email?: string;
  role?: UserRole;
  firstName?: string;
  lastName?: string;
  phone?: string;
  avatar?: Avatar;
  preferences?: UserPreferences;
  isActive?: boolean;
  isEmailVerified?: boolean;
  createdAt?: string;
}
